version: '3.9'

services:
  app_postgres:
    image: postgres:13
    container_name: app_postgres
    volumes:
      - ./pg_data/app:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
  django-app:
    image: django-app:latest
    container_name: django_app
    depends_on:
      - app_postgres
    volumes:
      - static_volumes:/app/static
      - media_volumes:/app/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 base.wsgi:application" 
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx
    container_name : app_nginx
    image: app_nginx
    volumes:
      - static_volumes:/app/static
      - media_volumes:/app/media
    depends_on:
      - app_postgres
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    

volumes:
  static_volumes:
  media_volumes:
  grafana_data:
  prometheus_data:
