global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["django-app:8000"]
    relabel_configs:
      - source_labels: [__adress__]
        regex: "([^:]+):\\d+"
        target_label: instance 