# Generated by Django 4.2.9 on 2024-02-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_staff', '0002_microcontoller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcontoller',
            name='category',
        ),
        migrations.RemoveField(
            model_name='microcontoller',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='microcontoller',
            name='user',
        ),
    ]
